services:
  api:
    image: ghcr.io/ungaul/applicator-api:latest
    restart: unless-stopped
    ports:
      - "8001:80"
    environment:
      - OPENROUTER_API_KEY=sk-or-xxxxx
      - OPENROUTER_MODEL=openai/gpt-4.1-mini
      - ADZUNA_APP_ID=xxx
      - ADZUNA_APP_KEY=xxx
      - JOB_SEARCHES=10

  app:
    image: ghcr.io/ungaul/applicator-app:latest
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - api